### PR TITLE
Fixed loading custom fields for sharpspring

### PR DESCRIPTION
**Pull request by LodeKennes**
The issue presented by @arnevanbael-axxes in PR #198 hadn't been fully fixed due to not putting "isCustom" in the "where" clause. Fully tested in a dev environment on Craft CMS. This fixes the issue.

### CODE REVIEW

**Comment by gustavs-gutmanis** [comment]
Thanks @LodeKennes

**Comment by LodeKennes** [comment]
No problem @gustavs-gutmanis, any idea when this will be released? A client of mine needs this. Thanks!

**Comment by gustavs-gutmanis** [comment]
Hopefully later today, but you can have your client install the `dev-master` version to get it right now

**Comment by LodeKennes** [comment]
@gustavs-gutmanis Don't want to sound pushy but any news on that release? 👼

**Comment by gustavs-gutmanis** [comment]
@kjmartens will know better, he's the one doing releases.

**Comment by kjmartens** [comment]
@LodeKennes this is released now in v3.11.11.1. 🙂

**Pull request merged**
