### PR TITLE
fix/v5/SFT-826: fix t.fields.filter

### PR DESCRIPTION
**Pull request by thejahid**
Field search in builder is not working when searching across forms. Gives `t.fields.filter is not a function` error

### CODE REVIEW

**Comment by gustavs-gutmanis** [comment]
What does this fix change?
It looks like the change is the same in terms of what it does as before.

**Comment by thejahid** [comment]
Yes but the previous one give object sometimes instead of array

**Comment by gustavs-gutmanis** [comment]
Ok, so then do this:

```php
$fields = array_map([$this->fieldTransformer, 'transform'], $fields);
$fields = array_values($fields);
```

**Comment by thejahid** [comment]
Yeah, that's correct, but isn't it re-indexing all the fields again? So I thought I'll do it one time.

**Review by kjmartens — APPROVED** [review]
Looks good

**Pull request merged**
