### PR TITLE
[SFT-1137][#1278]: Asset loading improvements

### PR DESCRIPTION
**Pull request by gustavs-gutmanis**
### Related Ticket Number
[SFT-1137](https://solspace.atlassian.net/browse/SFT-1137)
#1278

### Description
Loading assets with PHP and returning as files via `Response` was an ineffective way to handle asset transport to the front-end.  
And the existing approach with loading assets as files was sub-optimal.

This PR deprecates and removes the `Insert as Pointers` as an option from the settings, and defaults to `Insert as Files` by default for everyone that used either `Insert as Files` or `Insert as Pointers`

- refactor loading of published urls for assets with proper `path` and `filePath` paramters
- fix attribute attachment on inserted script tags
- deprecate `Insert as Pointers`
- default to `Insert as Files`
- remove all registered routes for loading assets as pointers

@timkelty, would it be possible for you to run this branch on a Craft Cloud install and see that everything is set up correctly?

I have taken inspiration from the #1286 PR, and adjusted the code to use your approach.

[SFT-1137]: https://solspace.atlassian.net/browse/SFT-1137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by timkelty** [comment]
@gustavs-gutmanis that works great!
Output urls now look something like this:
- https://cdn.craft.cloud/7d4a83b3-5fb0-4394-8f50-820514c95920/builds/9c1cda2f-cbef-4e1b-9271-ac204147dd74/cpresources/Solspace-Freeform-Resources/js/scripts/front-end/plugin/freeform.js?v=1716453346
- https://cdn.craft.cloud/7d4a83b3-5fb0-4394-8f50-820514c95920/builds/9c1cda2f-cbef-4e1b-9271-ac204147dd74/cpresources/Solspace-Freeform-Resources/js/scripts/front-end/captchas/recaptcha/v2-checkbox.js?v=1716453346

FYI - It looks like the description on the settings still needs to updated (still says stuff about the removed option)

**Comment by timkelty** [comment]
@gustavs-gutmanis FYI - The Solspace org on https://console.craftcms.com/ has a sandbox cloud project, so you can deploy and test these yourself as well.
Since we're using Freeform, I'm happy to test as well, just making sure you knew :)

**Review by kjmartens — CHANGES_REQUESTED** [review]
While this appears to work in my testing, I am concerned about anyone that might be depending on the Static URLs (aka `pointers`) approach. I also assume any cached templates may not work right after upgrade?

If we are actually to deprecate the `pointers` approach, it should at least continue to work for some period of time. If you are 100% certain that removing it will be okay for all users, there is one other scenario where this definitely becomes a breaking change:

If setting **Freeform Script Insertion Location** to _None_ and use `{{ freeform.loadFreeformPlugin() }}` manually in your template, this renders as:

``` html
<script type="text/javascript" src="https://site.test/freeform/plugin.js?v=f4ce7639d2f69410e807b6592a2935f7195fd95b" ></script>
<link rel="stylesheet" href="https://site.test/freeform/plugin.css?v=aff9fd861f04fe776cde9d8617f7a414d5d57b72"  />
```

And those URLs no longer exist, therefore breaking this approach.

Is it a lot of work to partially revert to continue to support `pointers` and/or `loadFreeformPlugin`?

**Comment by gustavs-gutmanis** [comment]
> @gustavs-gutmanis FYI - The Solspace org on https://console.craftcms.com/ has a sandbox cloud project, so you can deploy and test these yourself as well. Since we're using Freeform, I'm happy to test as well, just making sure you knew :)

Thanks, I will use that sandbox for testing from now on :)
Your help is greatly appreciated!

**Review by kjmartens — APPROVED** [review]

**Pull request merged**
